server:
  port: 8083
spring:
  profiles:
    active: contentmapper,commonspojo,redis
  application:
    name: baizhan-frontend-portal

eureka:
  client:
    service-url:
      defaultZone: http://172.16.145.151:8761/eureka/