server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://172.16.145.151:8761/eureka/
spring:
  profiles:
    active: itemmapper,redis
  application:
    name: baizhan-frontend-details
