spring:
  profiles:
    active: rabbitmq,redis,commonspojo,ordermapper,mail
  application:
    name: baizhan-middleware-rabbit-consumer
  elasticsearch:
    rest:
      uris: http://192.168.137.128:9200
tx-lcn:
  client:
    manager-address: 192.168.40.222:9190
eureka:
  client:
    service-url:
      defaultZone: http://172.16.145.151:8761/eureka/