spring:
  mail:
    #当前网站给别人发送邮件，使用哪个邮箱进行发送
    username: 570497606@qq.com
    #邮箱开启pop3/smtp后只显示一次的授权码
    password:
    #邮箱对应的主机
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          #开启邮箱客户端功能（通俗：能让邮箱通过代码发送邮件）
          auth: true

server:
  port: 9999
