server:
  port: 8088
spring:
  profiles:
    active: ordermapper,redis,rabbitmq
  application:
    name: baizhan-frontend-trade

eureka:
  client:
    service-url:
      defaultZone: http://172.16.145.151:8761/eureka/