spring:
  rabbitmq:
    host: 192.168.137.128
    username: bjsxt
    password: bjsxt
    port: 5672
baizhan:
  trade:
    mq:
      exchange: 'baizhan-trade-exchange'
      queuePrefix: 'baizhan-trade-queue-'  # 队列名称是 前缀+数字
      routingKeyPrefix: 'baizhan-trade-routing-key-'  # 路由键是 前缀+数字
      nums: 3  # 队列数量为3.
    redis:
      key: 'baizhan-trade-mq-sequence' # 提供MQ数字递增的redis key。 通过inc逻辑，实现数字递增。
    cartMQ:
      exchange: 'baizhan-trade-sync-cart'  # 同步购物车的交换器
      queue: 'baizhan-trade-sync-cart-queue' # 同步购物车的队列
      routingKey: 'baizhan-trade-sync-cart-routingKey' # 同步购物车路由键
    mailMQ:
      exchange: 'baizhan-trade-mail' # 发送邮件的交换器
      queue: 'baizhan-trade-mail-queue' # 发送邮件的队列