server:
  port: 8082

spring:
  application:
    name: baizhan-backend-content
  profiles:
    active: contentmapper,rabbitmq,redis

eureka:
  client:
    service-url:
      defaultZone: http://192.168.137.128:8761/eureka/